#!/bin/python3

import argparse
from random import randint
from sys import stdin


def main(): 
    MIN = 0
    MAX = 100
    N = 25
    S_IN = 0

    parser = argparse.ArgumentParser()
    parser.add_argument("-n", "--num") 
    parser.add_argument("--min", "-m")
    parser.add_argument("--max", "-M")
    parser.add_argument("--stdin", "-s", action="store_true")

    args = parser.parse_args()

    if args.num:
        N = int(args.num)
    if args.min:
        MIN = int(args.min)
    if args.max:
        MAX = int(args.max)  
    if args.stdin:
        S_IN = 1

    # comprueba que son argumentos válidos
    if MAX < MIN:
        print("MAX es menor que MIN")
        return
    if N < 0:
        print("N debe ser mayor que 0")
        return

    if S_IN:
        i = 0
        for numberLine in stdin:
            print(int(numberLine) + randint(MIN, MAX))
            i = i + 1
            
        while i <= N:
            print(randint(MIN, MAX))
            i = i + 1
    else:
        for _ in range(N):
            print(randint(MIN, MAX))
        

if __name__ == "__main__":
    main()